# @package _global_

defaults:
  - _self_
  - data: scared # choose datamodule with `test_dataloader()` for evaluation
  - model: overfit
  - logger: null
  - trainer: overfit
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: /bd_byta6000i0/users/surgical_depth/surgical_depth/logs/train/runs/2024-05-22_12-27-27/surgical_depth/1m74ji9o/checkpoints/epoch=307-step=1540.ckpt
